# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - 'test-tag-*'
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_VAR: "toto test var"
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
           echo Hello, world!
           echo "secret"
           echo ${{ secrets.TEST_TOKEN }}
           echo "toto"
           echo $TEST_VAR
           echo "toto2"
           
      - name: Checkout repo knl-sdk-ios
        uses: actions/checkout@v2
        with:
          repository: Kannelle-io/knl-sdk-ios      
          ref: 3.0.1
          path: .
          token: ${{ secrets.KANNELLE_PAT }}

      - name: Checkout repo knl-sdk-ios-rn
        uses: actions/checkout@v2
        with:
          repository: Kannelle-io/knl-sdk-ios-rn     
          ref: 3.0.1
          path: .
          token: ${{ secrets.KANNELLE_PAT }}
      
      - name: Setup bundle env
        run: |   
          echo $PWD
          echo $(ls)       
   
