# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - 'test-tag-*'
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main
       
      - uses: actions/setup-node@v2
        with:      
          node-version: '16'

      - name: Checkout repo knl-app
        uses: actions/checkout@v2
        with:
          repository: Kannelle-io/knl-app
          ref: ft-scenario-native-view-ios-github-action
          path: knl-app
          token: ${{ secrets.KANNELLE_PAT }}
                 
      - name: Checkout repo knl-sdk-ios
        uses: actions/checkout@v2
        with:
          repository: Kannelle-io/knl-sdk-ios      
          ref: 3.0.1
          path: knl-sdk-ios  
          token: ${{ secrets.KANNELLE_PAT }}

      - name: Checkout repo knl-sdk-ios-rn
        uses: actions/checkout@v2
        with:
          repository: Kannelle-io/knl-sdk-ios-rn     
          ref: 3.0.1
          path: knl-sdk-ios-rn 
          token: ${{ secrets.KANNELLE_PAT }}        
         
      - name: Git credentials for npm install
        run: |
          REPO_URL="https://github.com/Kannelle-io/react-native-simple-store.git"
          git config --global --add http.$REPO_URL.extraHeader "Authorization: Basic ${{ secrets.KANNELLE_PAT_BASE64 }}" 
          REPO_URL2="https://github.com/Kannelle-io/react-native-camera.git"
          git config --global --add http.$REPO_URL2.extraHeader "Authorization: Basic ${{ secrets.KANNELLE_PAT_BASE64 }}"
          REPO_URL3="https://github.com/Kannelle-io/knl-sdk-ios.git"
          git config --global --add http.$REPO_URL3.extraHeader "Authorization: Basic ${{ secrets.KANNELLE_PAT_BASE64 }}" 
          REPO_URL4="https://github.com/Kannelle-io/knl-sdk-ios-rn.git"
          git config --global --add http.$REPO_URL4.extraHeader "Authorization: Basic ${{ secrets.KANNELLE_PAT_BASE64 }}" 
      
      - name: Setup bundle env
        run: |          
          npm install typescript -g
          
      - name: Setup bundle env
        run: |          
          cd knl-app/ios          
          bundle install
      
      - name: Fastlane match
        run: |          
          cd knl-app/ios  
          bundle exec fastlane match appstore --readonly
      
      - name: Fastlane release staging        
        run: |          
          cd knl-app/ios  
          bundle exec fastlane release --env staging
