# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - 'test-tag-*'
      - 'i-*-stage'
      - 'i-*'
#    branches:
#      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main
   
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
   
      - name: Get the version
        id: get_env
        run: |
          ENV="prod"
          if [[ ${{ steps.get_version.outputs.VERSION }} == "stage" ]]; then
            ENV="stage"        
          fi
          echo ::set-output name=ENV::ENV
   
      - name: Setup tools
        run: |          
          echo "version"
          echo ${{ steps.get_env.outputs.ENV }}
          

